variable "image_name" {}
variable "ddclient_username" {}
variable "ddclient_password" {}
variable "ddclient_hostname" {}
variable "ddclient_server" {}
variable "ddclient_protocol" {}
variable "ddclient_daemon_interval" {}
variable "vol_path" {}
variable "nfs_server" {}
variable "storage_capacity" {}
